"""add culture facilities association table

Revision ID: 09bc71264012
Revises: 8501f7412345
Create Date: 2026-06-17 17:38:13.037477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09bc71264012'
down_revision = '8501f7412345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('culture_facilities', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('culture_facilities_facility_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('culture_facilities_culture_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'culture_sites', ['culture_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'facilities', ['facility_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('culture_facilities', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('culture_facilities_culture_id_fkey'), 'culture_sites', ['culture_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('culture_facilities_facility_id_fkey'), 'facilities', ['facility_id'], ['id'])

    # ### end Alembic commands ###
