"""add_reminder_flags_to_favorites

Revision ID: 108052b1f28a
Revises: afaf62a5bfbe
Create Date: 2026-07-10 06:37:26.040432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '108052b1f28a'
down_revision = 'afaf62a5bfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_1h_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('reminder_start_sent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_favorites', schema=None) as batch_op:
        batch_op.drop_column('reminder_start_sent')
        batch_op.drop_column('reminder_1h_sent')

    # ### end Alembic commands ###
