"""add_strict_uuid_mapping_to_scrape_targets

Revision ID: 334c2e086d78
Revises: 186d9f71229d
Create Date: 2026-07-10 07:47:30.848510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334c2e086d78'
down_revision = '186d9f71229d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_targets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_id', sa.UUID(), nullable=False))
        batch_op.add_column(sa.Column('target_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scrape_targets', schema=None) as batch_op:
        batch_op.drop_column('target_type')
        batch_op.drop_column('target_id')

    # ### end Alembic commands ###
