"""Initial migration

Revision ID: 3c7c555711eb
Revises: 
Create Date: 2026-05-19 17:32:39.788632

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c7c555711eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_badge', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('syarat_poin', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_fasilitas', sa.String(length=100), nullable=False),
    sa.Column('icon_key', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('no_telp', sa.String(length=20), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=50), nullable=True),
    sa.Column('poin', sa.Integer(), nullable=True),
    sa.Column('total_xp', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('onesignal_id', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('culture_sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_tempat', sa.String(length=150), nullable=False),
    sa.Column('subtitle', sa.String(length=150), nullable=True),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('tahun_dibangun', sa.String(length=50), nullable=True),
    sa.Column('lokasi_singkat', sa.String(length=100), nullable=True),
    sa.Column('durasi_kunjungan', sa.String(length=50), nullable=True),
    sa.Column('jarak_estimasi', sa.String(length=50), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('fun_fact', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('gallery', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('is_slider', sa.Boolean(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judul_event', sa.String(length=150), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tanggal_lengkap', sa.String(length=100), nullable=False),
    sa.Column('waktu_pelaksanaan', sa.String(length=100), nullable=False),
    sa.Column('lokasi_singkat', sa.String(length=100), nullable=False),
    sa.Column('alamat_lengkap', sa.Text(), nullable=False),
    sa.Column('audience', sa.String(length=100), nullable=False),
    sa.Column('harga_tiket', sa.String(length=50), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('highlights', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('badge_top', sa.String(length=50), nullable=True),
    sa.Column('badge_bottom', sa.String(length=50), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('judul', sa.String(length=200), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('tanggal', sa.Date(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('konten', sa.Text(), nullable=False),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('komentar', sa.Text(), nullable=False),
    sa.Column('review_image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('umkms',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_produk', sa.String(length=150), nullable=False),
    sa.Column('harga', sa.String(length=50), nullable=False),
    sa.Column('nama_toko', sa.String(length=100), nullable=False),
    sa.Column('kategori', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('alamat_toko', sa.Text(), nullable=True),
    sa.Column('no_whatsapp', sa.String(length=20), nullable=True),
    sa.Column('link_eksternal', sa.String(length=255), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_badges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('badge_id', sa.UUID(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('culture_facilities',
    sa.Column('culture_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['culture_id'], ['culture_sites.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ),
    sa.PrimaryKeyConstraint('culture_id', 'facility_id')
    )
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('culture_id', sa.UUID(), nullable=True),
    sa.Column('pertanyaan', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('opsi_jawaban', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jawaban_benar', sa.String(length=10), nullable=False),
    sa.Column('poin_reward', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['culture_id'], ['culture_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scan_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('scan_method', sa.String(length=50), nullable=False),
    sa.Column('poin_didapat', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['culture_sites.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_quiz_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_quiz_history')
    op.drop_table('scan_history')
    op.drop_table('quizzes')
    op.drop_table('culture_facilities')
    op.drop_table('user_favorites')
    op.drop_table('user_badges')
    op.drop_table('umkms')
    op.drop_table('reviews')
    op.drop_table('news')
    op.drop_table('events')
    op.drop_table('culture_sites')
    op.drop_table('users')
    op.drop_table('facilities')
    op.drop_table('badges')
    # ### end Alembic commands ###
