"""add_coordinate_and_contact_to_umkms

Revision ID: 619e62314a72
Revises: 09bc71264012
Create Date: 2026-06-26 02:23:19.887921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619e62314a72'
down_revision = '09bc71264012'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umkms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('umkms', schema=None) as batch_op:
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    # ### end Alembic commands ###
