"""add raw_end_date column

Revision ID: 8501f7412345
Revises: 00b47ada4018
Create Date: 2026-05-19 22:18:03.576835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8501f7412345'
down_revision = '00b47ada4018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_end_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('raw_end_date')

    # ### end Alembic commands ###
