"""integrate_gamification_ai_and_scrape_targets

Revision ID: bea75fd2f656
Revises: f130003d0db2
Create Date: 2026-07-10 06:10:21.984239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea75fd2f656'
down_revision = 'f130003d0db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_targets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama_tempat', sa.String(length=150), nullable=False),
    sa.Column('url_maps', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scrape_targets')
    # ### end Alembic commands ###
