"""add_food_id_in_queez

Revision ID: c93177f01ccf
Revises: d90ceba5e1b3
Create Date: 2026-07-12 12:42:37.340512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93177f01ccf'
down_revision = 'd90ceba5e1b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('food_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'food_metadata', ['food_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('food_id')

    # ### end Alembic commands ###
