"""add_food_metadata_and_normalize_ai_scan_history

Revision ID: f130003d0db2
Revises: f0853d06f6c2
Create Date: 2026-07-10 05:03:47.397838

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f130003d0db2'
down_revision = 'f0853d06f6c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_metadata',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('label_key', sa.String(length=100), nullable=False),
    sa.Column('nama_makanan', sa.String(length=150), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('label_key')
    )
    with op.batch_alter_table('ai_scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_label', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('food_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(None, 'food_metadata', ['food_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('video_url')
        batch_op.drop_column('deskripsi')
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_scan_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('deskripsi', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('video_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('food_id')
        batch_op.drop_column('predicted_label')

    op.drop_table('food_metadata')
    # ### end Alembic commands ###
